disabled = false
languageCode = "en"
languageName = "English"
title = "P3R/gelidis"
weight = 1

[params]
dateFormat = "2 January 2006"
displayName = "EN"
isoCode = "en"
logo = "img/logo.png"
rtl = false
description = "P3R | Dimitris Pergelidis"
author = { bio = "IT Security Engineer @ GRNET", email = "dim.pergel@gmail.com", headline = "IT Security Engineer @ GRNET", image = "img/profile.png", imageQuality = 96, links = [ { email = "mailto:dim.pergel@gmail.com" }, { github = "https://github.com/p3rception" }, { linkedin = "https://linkedin.com/in/dimitrisper" } ], name = "Dimitris Pergelidis" }
