disabled = false
languageCode = "en"
languageName = "English"
title = "Dimitris (p3r)gelidis"
weight = 1

[params]
dateFormat = "2 January 2006"
displayName = "EN"
isoCode = "en"
logo = "img/dp-stroke-small.png"
secondaryLogo = "img/dp-stroke-small-inverted.png"
rtl = false
copyright = "&copy; 2024 | Dimitris Pergelidis"

description = "P3R | Dimitris Pergelidis"
author = { bio = "IT Security Engineer @ GRNET", email = "dim.pergel@gmail.com", headline = "IT Security Engineer @ GRNET", image = "img/profile_no_bg.png", imageQuality = 96, links = [
   # { email = "mailto:dim.pergel@gmail.com" },
   { github = "https://github.com/p3rception" },
   { htb = "https://app.hackthebox.com/profile/968175" },
   { linkedin = "https://linkedin.com/in/dimitrisper" },

], name = "Dimitris Pergelidis" }
